import localFont from "next/font/local";
import Providers from "../../components/providers";
import ".././globals.css";

const poppins = localFont({
  src: [
    {
      path: '../fonts/Poppins-Regular.ttf',
      weight: '400'
    },
    {
      path: '../fonts/Poppins-Medium.ttf',
      weight: '500'
    },
    {
      path: '../fonts/Poppins-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-poppins'
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <Providers>
      <body>{children}</body>
      </Providers>
      
    </html>
  )
}
