FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/bank_webhook_handler ./apps/bank_webhook_handler
COPY packages ./packages

# Install dependencies
RUN npm install

RUN npm run prisma

RUN npm run user-build

CMD ["npm", "run","start-user-app"]