FROM node:latest


WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

RUN npm run prisma

RUN npm run user-build

CMD ["npm", "run","start-user-app"]