FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps/user-app ./apps/user-app
COPY packages ./packages

# Install dependencies
RUN npm install

RUN npm run prisma

RUN npm run bank-webhook-build

CMD ["npm", "run","start-bank-webhook"]