
import type { Metadata } from "next";
import localFont from "next/font/local";
import ".././globals.css";
import Providers from "../../components/providers";
import AppbarClient from "../../components/Appbar";



const geistSans = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Paytm App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AppbarClient/>
        {children}  
      </body>
      </Providers>
      
    </html>
  );
}
