name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push user-app Docker image
        run: |
          docker build -f ./docker/Dockerfile.user -t kapilvashisht/paytm:latest .
          docker push kapilvashisht/paytm:latest

      - name: Build and Push bank-webhook-server Docker image
        run: |
          docker build -f ./docker/Dockerfile.bank -t kapilvashisht/paytm-bankserver:latest .
          docker push kapilvashisht/paytm-bankserver:latest

      - name: Verify Pushed Images
        run: |
          docker pull kapilvashisht/paytm:latest
          docker pull kapilvashisht/paytm-bankserver:latest
