name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: kapilvashisht/frontend:latest

      - name: Build and Push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bank
          push: true
          tags: kapilvashisht/backend:latest

      - name: Verify Pushed Frontend Image
        run: docker pull kapilvashisht/frontend:latest

      - name: Verify Pushed Backend Image
        run: docker pull kapilvashisht/backend:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_SSH_HOST }}
          username: ${{ secrets.AZURE_SSH_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            sudo docker pull kapilvashisht/frontend:latest
            sudo docker pull kapilvashisht/backend:latest

            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker stop backend || true
            sudo docker rm backend || true

            sudo docker run -d --name frontend -p 3000:3000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET }}" \
              -e NEXT_AUTH_URL="${{ secrets.NEXT_AUTH_URL }}" \
              -e WEBHOOK_URL="${{ secrets.WEBHOOK_URL }}" \
              kapilvashisht/frontend:latest

            sudo docker run -d --name backend -p 3003:3003 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e SECRET="${{ secrets.SECRET }}" \
              kapilvashisht/backend:latest
